const modalData = [
  {
    "user_id": 1,
    "user_nickname": "푸바오귀여워",
    "user_age": "10",
    "user_sex": "F",
    "user_tag1": "FLEX",
    "user_tag2": "철두철미",
    "user_tag3": "호캉스",
    "user_distance": 1,
    "user_country": "Indonesia",
    "user_travel_start": "2023-06-02",
    "user_travel_end": "2023-07-11",
    "user_image": "https://images.unsplash.com/photo-1529665253569-6d01c0eaf7b6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=785&q=80",
    "user_sns": "viva121"
  },
  {
    "user_id": 2,
    "user_nickname": "여행조하",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "절약정신",
    "user_tag2": "즉흥적인",
    "user_tag3": "여행초보",
    "user_distance": 2,
    "user_country": "Canada",
    "user_travel_start": "2023-01-23",
    "user_travel_end": "2023-07-09",
    "user_image": "https://images.unsplash.com/photo-1511367461989-f85a21fda167?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHJvZmlsZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=1000&q=60",
    "user_sns": "vagram24"
  },
  {
    "user_id": 3,
    "user_nickname": "여행덕후",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "무계획",
    "user_tag2": "맛집탐방",
    "user_tag3": "관광",
    "user_distance": 2,
    "user_country": "Philippines",
    "user_travel_start": "2023-04-02",
    "user_travel_end": "2023-07-27",
    "user_image": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cHJvZmlsZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=1000&q=60",
    "user_sns": "bitwolf867"
  },
  {
    "user_id": 4,
    "user_nickname": "헨델과그랬데",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "외국어",
    "user_tag2": "쇼핑",
    "user_tag3": "적극적인",
    "user_distance": 3,
    "user_country": "Czech Republic",
    "user_travel_start": "2023-01-16",
    "user_travel_end": "2023-11-15",
    "user_image": "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "user_sns": "1uo_lux"
  },
  {
    "user_id": 5,
    "user_nickname": "조선왕조씰룩",
    "user_age": "30",
    "user_sex": "M",
    "user_tag1": "외향적인",
    "user_tag2": "드라이브",
    "user_tag3": "무계획",
    "user_distance": 3,
    "user_country": "Peru",
    "user_travel_start": "2023-02-26",
    "user_travel_end": "2023-12-10",
    "user_image": "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "user_sns": "daltfresh12"
  },
  {
    "user_id": 6,
    "user_nickname": "아기공룡둘째",
    "user_age": "30",
    "user_sex": "M",
    "user_tag1": "카페탐방",
    "user_tag2": "여행초보",
    "user_tag3": "계획적인",
    "user_distance": 3,
    "user_country": "Serbia",
    "user_travel_start": "2023-06-19",
    "user_travel_end": "2023-12-28",
    "user_image": "https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "user_sns": "stim903"
  },
  {
    "user_id": 7,
    "user_nickname": "반지하의제왕",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "사진찍는",
    "user_tag2": "활동적인",
    "user_tag3": "여행고수",
    "user_distance": 4,
    "user_country": "France",
    "user_travel_start": "2023-06-12",
    "user_travel_end": "2023-11-28",
    "user_image": "https://images.pexels.com/photos/1499327/pexels-photo-1499327.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "user_sns": "transcofy654"
  },
  {
    "user_id": 8,
    "user_nickname": "조선왕조쌜룩",
    "user_age": "40",
    "user_sex": "F",
    "user_tag1": "여행고수",
    "user_tag2": "쇼핑",
    "user_tag3": "외국어",
    "user_distance": 4,
    "user_country": "Russia",
    "user_travel_start": "2023-03-02",
    "user_travel_end": "2023-10-08",
    "user_image": "https://images.pexels.com/photos/678783/pexels-photo-678783.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "cardify"
  },
  {
    "user_id": 9,
    "user_nickname": "귀신이고칼로리",
    "user_age": "40",
    "user_sex": "M",
    "user_tag1": "드라이브",
    "user_tag2": "캠핑",
    "user_tag3": "등산",
    "user_distance": 4,
    "user_country": "Russia",
    "user_travel_start": "2023-05-16",
    "user_travel_end": "2023-12-28",
    "user_image": "https://images.pexels.com/photos/1080213/pexels-photo-1080213.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "konklab564"
  },
  {
    "user_id": 10,
    "user_nickname": "단칸방고양이",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "사진찍는",
    "user_tag2": "즉흥적인",
    "user_tag3": "여행초보",
    "user_distance": 4,
    "user_country": "Peru",
    "user_travel_start": "2023-04-08",
    "user_travel_end": "2023-12-04",
    "user_image": "https://images.pexels.com/photos/2589653/pexels-photo-2589653.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "bamity425"
  },
  {
    "user_id": 11,
    "user_nickname": "오이날다",
    "user_age": "30",
    "user_sex": "M",
    "user_tag1": "글램핑",
    "user_tag2": "무계획",
    "user_tag3": "외향적인",
    "user_distance": 5,
    "user_country": "Indonesia",
    "user_travel_start": "2023-01-06",
    "user_travel_end": "2023-11-11",
    "user_image": "https://images.pexels.com/photos/1081685/pexels-photo-1081685.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "fintone978"
  },
  {
    "user_id": 12,
    "user_nickname": "많이큰젝슨",
    "user_age": "10",
    "user_sex": "F",
    "user_tag1": "즉흥적인",
    "user_tag2": "적극적인",
    "user_tag3": "FLEX",
    "user_distance": 5,
    "user_country": "Indonesia",
    "user_travel_start": "2023-06-20",
    "user_travel_end": "2023-09-06",
    "user_image": "https://images.pexels.com/photos/1547971/pexels-photo-1547971.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "zamit5789"
  },
  {
    "user_id": 13,
    "user_nickname": "아침마담",
    "user_age": "50",
    "user_sex": "M",
    "user_tag1": "뚜벅이",
    "user_tag2": "카페탐방",
    "user_tag3": "사진찍는",
    "user_distance": 5,
    "user_country": "Philippines",
    "user_travel_start": "2023-01-01",
    "user_travel_end": "2023-12-20",
    "user_image": "https://images.pexels.com/photos/428361/pexels-photo-428361.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "quoux890"
  },
  {
    "user_id": 14,
    "user_nickname": "아리아나그런데",
    "user_age": "10",
    "user_sex": "F",
    "user_tag1": "절약정신",
    "user_tag2": "여행초보",
    "user_tag3": "관광",
    "user_distance": 5,
    "user_country": "Japan",
    "user_travel_start": "2023-04-13",
    "user_travel_end": "2023-11-24",
    "user_image": "https://images.pexels.com/photos/1484810/pexels-photo-1484810.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "hatity21"
  },
  {
    "user_id": 15,
    "user_nickname": "벼랑위의당뇨",
    "user_age": "20",
    "user_sex": "M",
    "user_tag1": "맛집탐방",
    "user_tag2": "드라이브",
    "user_tag3": "호캉스",
    "user_distance": 5,
    "user_country": "Indonesia",
    "user_travel_start": "2023-01-01",
    "user_travel_end": "2023-11-01",
    "user_image": "https://images.pexels.com/photos/3779760/pexels-photo-3779760.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "otcomrt"
  },
  {
    "user_id": 16,
    "user_nickname": "긴박한박대",
    "user_age": "30",
    "user_sex": "M",
    "user_tag1": "무계획",
    "user_tag2": "쇼핑",
    "user_tag3": "즉흥적인",
    "user_distance": 6,
    "user_country": "China",
    "user_travel_start": "2023-03-26",
    "user_travel_end": "2023-12-05",
    "user_image": "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "alpha_zap"
  },
  {
    "user_id": 17,
    "user_nickname": "카드값줘체리",
    "user_age": "40",
    "user_sex": "M",
    "user_tag1": "FLEX",
    "user_tag2": "철두철미​",
    "user_tag3": "외향적인",
    "user_distance": 7,
    "user_country": "Sweden",
    "user_travel_start": "2023-01-06",
    "user_travel_end": "2023-08-08",
    "user_image": "https://images.pexels.com/photos/1370750/pexels-photo-1370750.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "big_qwtax254"
  },
  {
    "user_id": 18,
    "user_nickname": "소잃고고쳐",
    "user_age": "50",
    "user_sex": "F",
    "user_tag1": "드라이브",
    "user_tag2": "FLEX",
    "user_tag3": "쇼핑",
    "user_distance": 8,
    "user_country": "Philippines",
    "user_travel_start": "2023-06-14",
    "user_travel_end": "2023-07-11",
    "user_image": "https://images.pexels.com/photos/2076596/pexels-photo-2076596.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "an_dalax99"
  },
  {
    "user_id": 19,
    "user_nickname": "시베리안허숙희",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "여행고수",
    "user_tag2": "계획적인",
    "user_tag3": "절약정신",
    "user_distance": 10,
    "user_country": "Yemen",
    "user_travel_start": "2023-01-20",
    "user_travel_end": "2023-12-28",
    "user_image": "https://images.pexels.com/photos/34534/people-peoples-homeless-male.jpg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "solowarm_.31"
  },
  {
    "user_id": 20,
    "user_nickname": "잠오는마녀",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "소심한",
    "user_tag2": "잘따르는",
    "user_tag3": "여행초보",
    "user_distance": 12,
    "user_country": "Philippines",
    "user_travel_start": "2023-06-23",
    "user_travel_end": "2023-11-23",
    "user_image": "https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "subin0_9"
  },
  {
    "user_id": 21,
    "user_nickname": "봉구스박보검",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "외국어",
    "user_tag2": "적극적인",
    "user_tag3": "여행고수",
    "user_distance": 11,
    "user_country": "Argentina",
    "user_travel_start": "2023-06-17",
    "user_travel_end": "2023-10-25",
    "user_image": "https://images.pexels.com/photos/810775/pexels-photo-810775.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "yy_solowarm"
  },
  {
    "user_id": 22,
    "user_nickname": "아줌마가대왕",
    "user_age": "10",
    "user_sex": "F",
    "user_tag1": "철두철미",
    "user_tag2": "호캉스᠎",
    "user_tag3": "적극적인",
    "user_distance": 12,
    "user_country": "Germany",
    "user_travel_start": "2023-02-14",
    "user_travel_end": "2023-07-29",
    "user_image": "https://images.pexels.com/photos/838413/pexels-photo-838413.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "fix_flex._.0"
  },
  {
    "user_id": 23,
    "user_nickname": "트래블메이커",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "뚜벅이",
    "user_tag2": "명소 탐방",
    "user_tag3": "외국어",
    "user_distance": 13,
    "user_country": "France",
    "user_travel_start": "2023-06-05",
    "user_travel_end": "2023-10-20",
    "user_image": "https://images.pexels.com/photos/2027821/pexels-photo-2027821.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "gem_bucket76"
  },
  {
    "user_id": 24,
    "user_nickname": "여행과결혼",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "사진찍는",
    "user_tag2": "활동적인",
    "user_tag3": "외향적인",
    "user_distance": 14,
    "user_country": "Indonesia",
    "user_travel_start": "2023-05-26",
    "user_travel_end": "2023-11-20",
    "user_image": "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "bigbox_897"
  },
  {
    "user_id": 25,
    "user_nickname": "짜장면짬뽕",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "절약정신",
    "user_tag2": "소심한",
    "user_tag3": "외국어",
    "user_distance": 15,
    "user_country": "Russia",
    "user_travel_start": "2023-01-15",
    "user_travel_end": "2023-09-04",
    "user_image": "https://images.pexels.com/photos/2589650/pexels-photo-2589650.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "it_love982"
  },
  {
    "user_id": 26,
    "user_nickname": "콩쥐들쥐",
    "user_age": "10",
    "user_sex": "M",
    "user_tag1": "FLEX",
    "user_tag2": "여행초보",
    "user_tag3": "적극적인",
    "user_distance": 1,
    "user_country": "France",
    "user_travel_start": "2023-05-02",
    "user_travel_end": "2023-08-23",
    "user_image": "https://images.pexels.com/photos/1906157/pexels-photo-1906157.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "rank123"
  },
  {
    "user_id": 27,
    "user_nickname": "욕조숙녀",
    "user_age": "10",
    "user_sex": "F",
    "user_tag1": "여행초보",
    "user_tag2": "적극적인",
    "user_tag3": "음주선호",
    "user_distance": 2,
    "user_country": "Bolivia",
    "user_travel_start": "2023-06-15",
    "user_travel_end": "2023-11-21",
    "user_image": "https://images.pexels.com/photos/4906334/pexels-photo-4906334.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "kanlam_1"
  },
  {
    "user_id": 28,
    "user_nickname": "빚과송금",
    "user_age": "10",
    "user_sex": "F",
    "user_tag1": "외국어",
    "user_tag2": "사진찍는",
    "user_tag3": "적극적인",
    "user_distance": 3,
    "user_country": "Argentina",
    "user_travel_start": "2023-05-28",
    "user_travel_end": "2023-10-27",
    "user_image": "https://images.pexels.com/photos/2918513/pexels-photo-2918513.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "treeflex_12"
  },
  {
    "user_id": 29,
    "user_nickname": "올리브깡",
    "user_age": "10",
    "user_sex": "M",
    "user_tag1": "여행초보",
    "user_tag2": "사진찍는",
    "user_tag3": "계획적인",
    "user_distance": 4,
    "user_country": "Indonesia",
    "user_travel_start": "2023-05-04",
    "user_travel_end": "2023-12-08",
    "user_image": "https://images.pexels.com/photos/1615776/pexels-photo-1615776.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "matsoft_55"
  },
  {
    "user_id": 30,
    "user_nickname": "순데될라",
    "user_age": "10",
    "user_sex": "F",
    "user_tag1": "느긋한",
    "user_tag2": "사진찍는",
    "user_tag3": "FLEX",
    "user_distance": 5,
    "user_country": "China",
    "user_travel_start": "2023-02-06",
    "user_travel_end": "2023-08-05",
    "user_image": "https://images.pexels.com/photos/1194806/pexels-photo-1194806.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "t_i_n"
  },
  {
    "user_id": 31,
    "user_nickname": "벼락식혜",
    "user_age": "10",
    "user_sex": "M",
    "user_tag1": "계획적인",
    "user_tag2": "뚜벅이",
    "user_tag3": "FLEX",
    "user_distance": 6,
    "user_country": "Ukraine",
    "user_travel_start": "2023-05-30",
    "user_travel_end": "2023-12-09",
    "user_image": "https://images.pexels.com/photos/3574678/pexels-photo-3574678.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "do_m-ainer1"
  },
  {
    "user_id": 32,
    "user_nickname": "여운계다",
    "user_age": "20",
    "user_sex": "M",
    "user_tag1": "뚜벅이",
    "user_tag2": "내향적인",
    "user_tag3": "사진찍는",
    "user_distance": 7,
    "user_country": "Philippines",
    "user_travel_start": "2023-04-30",
    "user_travel_end": "2023-08-17",
    "user_image": "https://images.pexels.com/photos/681637/pexels-photo-681637.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "bio_dex1_2"
  },
  {
    "user_id": 33,
    "user_nickname": "휴지필름",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "계획적인",
    "user_tag2": "적극적인",
    "user_tag3": "사진찍는",
    "user_distance": 8,
    "user_country": "Nigeria",
    "user_travel_start": "2023-03-02",
    "user_travel_end": "2023-09-25",
    "user_image": "https://images.pexels.com/photos/1031081/pexels-photo-1031081.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "p_rodde_2r"
  },
  {
    "user_id": 34,
    "user_nickname": "쾌변춘향",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "즉흥적인",
    "user_tag2": "사진찍는",
    "user_tag3": "여행초보",
    "user_distance": 9,
    "user_country": "Portugal",
    "user_travel_start": "2023-03-05",
    "user_travel_end": "2023-07-30",
    "user_image": "https://images.pexels.com/photos/1590483/pexels-photo-1590483.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "temps_oft_1"
  },
  {
    "user_id": 35,
    "user_nickname": "공익인간",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "계획적인",
    "user_tag2": "외향적인",
    "user_tag3": "사진찍는",
    "user_distance": 10,
    "user_country": "China",
    "user_travel_start": "2023-06-16",
    "user_travel_end": "2023-11-01",
    "user_image": "https://images.pexels.com/photos/1054251/pexels-photo-1054251.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "treef_lex"
  },
  {
    "user_id": 36,
    "user_nickname": "궁민연금",
    "user_age": "20",
    "user_sex": "F",
    "user_tag1": "여행초보",
    "user_tag2": "뚜벅이",
    "user_tag3": "음주선호",
    "user_distance": 1,
    "user_country": "China",
    "user_travel_start": "2023-02-14",
    "user_travel_end": "2023-09-08",
    "user_image": "https://images.pexels.com/photos/1278566/pexels-photo-1278566.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "konkl_ux_55"
  },
  {
    "user_id": 37,
    "user_nickname": "톱과젤리",
    "user_age": "20",
    "user_sex": "M",
    "user_tag1": "적극적인",
    "user_tag2": "사진찍는",
    "user_tag3": "느긋한",
    "user_distance": 2,
    "user_country": "China",
    "user_travel_start": "2023-05-25",
    "user_travel_end": "2023-10-12",
    "user_image": "https://images.pexels.com/photos/2340978/pexels-photo-2340978.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "car_dify_123"
  },
  {
    "user_id": 38,
    "user_nickname": "태조샷건",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "내향적인",
    "user_tag2": "사진찍는",
    "user_tag3": "즉흥적인",
    "user_distance": 3,
    "user_country": "China",
    "user_travel_start": "2023-02-28",
    "user_travel_end": "2023-07-26",
    "user_image": "https://images.pexels.com/photos/3792581/pexels-photo-3792581.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "s_onai_r"
  },
  {
    "user_id": 39,
    "user_nickname": "니콜키크드만",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "적극적인",
    "user_tag2": "외향적인",
    "user_tag3": "사진찍는",
    "user_distance": 4,
    "user_country": "Russia",
    "user_travel_start": "2023-03-26",
    "user_travel_end": "2023-07-22",
    "user_image": "https://images.pexels.com/photos/3775540/pexels-photo-3775540.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "mats_ft_1"
  },
  {
    "user_id": 40,
    "user_nickname": "달려라뭐하니",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "사진찍는",
    "user_tag2": "FLEX",
    "user_tag3": "적극적인",
    "user_distance": 5,
    "user_country": "Philippines",
    "user_travel_start": "2023-06-21",
    "user_travel_end": "2023-07-24",
    "user_image": "https://images.pexels.com/photos/947639/pexels-photo-947639.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "f_ma_iner"
  },
  {
    "user_id": 41,
    "user_nickname": "체험살해현장",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "즉흥적인",
    "user_tag2": "뚜벅이",
    "user_tag3": "드라이버",
    "user_distance": 6,
    "user_country": "Indonesia",
    "user_travel_start": "2023-05-03",
    "user_travel_end": "2023-10-16",
    "user_image": "https://images.pexels.com/photos/1153334/pexels-photo-1153334.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "hl_dla_mis"
  },
  {
    "user_id": 42,
    "user_nickname": "옥다방고양이",
    "user_age": "30",
    "user_sex": "M",
    "user_tag1": "즉흥적인",
    "user_tag2": "느긋한",
    "user_tag3": "외국어",
    "user_distance": 7,
    "user_country": "China",
    "user_travel_start": "2023-03-20",
    "user_travel_end": "2023-11-26",
    "user_image": "https://images.pexels.com/photos/3763152/pexels-photo-3763152.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "t_oughjoy_fax"
  },
  {
    "user_id": 43,
    "user_nickname": "티끌모아파산",
    "user_age": "30",
    "user_sex": "F",
    "user_tag1": "즉흥적인",
    "user_tag2": "뚜벅이",
    "user_tag3": "느긋한",
    "user_distance": 8,
    "user_country": "Sweden",
    "user_travel_start": "2023-03-06",
    "user_travel_end": "2023-08-19",
    "user_image": "https://images.pexels.com/photos/1370719/pexels-photo-1370719.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "y_Sol_owarm"
  },
  {
    "user_id": 44,
    "user_nickname": "벼랑위의당뇨",
    "user_age": "40",
    "user_sex": "F",
    "user_tag1": "계획적인",
    "user_tag2": "느긋한",
    "user_tag3": "FLEX",
    "user_distance": 9,
    "user_country": "Sweden",
    "user_travel_start": "2023-04-30",
    "user_travel_end": "2023-10-01",
    "user_image": "https://images.pexels.com/photos/246805/pexels-photo-246805.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "greenla-22"
  },
  {
    "user_id": 45,
    "user_nickname": "독도는록시땅",
    "user_age": "40",
    "user_sex": "F",
    "user_tag1": "사진찍는",
    "user_tag2": "외국어",
    "user_tag3": "FLEX",
    "user_distance": 10,
    "user_country": "Russia",
    "user_travel_start": "2023-01-02",
    "user_travel_end": "2023-12-26",
    "user_image": "https://images.pexels.com/photos/2080383/pexels-photo-2080383.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "fix_Sa_1n"
  },
  {
    "user_id": 46,
    "user_nickname": "축구왕숏다리",
    "user_age": "40",
    "user_sex": "M",
    "user_tag1": "즉흥적인",
    "user_tag2": "사진찍는",
    "user_tag3": "FLEX",
    "user_distance": 1,
    "user_country": "China",
    "user_travel_start": "2023-06-23",
    "user_travel_end": "2023-12-11",
    "user_image": "https://images.pexels.com/photos/1161668/pexels-photo-1161668.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "d_2_obam"
  },
  {
    "user_id": 47,
    "user_nickname": "아기공룡둘째",
    "user_age": "40",
    "user_sex": "F",
    "user_tag1": "외향적인",
    "user_tag2": "적극적인",
    "user_tag3": "사진 찍는",
    "user_distance": 2,
    "user_country": "Philippines",
    "user_travel_start": "2023-06-18",
    "user_travel_end": "2023-11-14",
    "user_image": "https://images.pexels.com/photos/3492736/pexels-photo-3492736.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "t_2_2in"
  },
  {
    "user_id": 48,
    "user_nickname": "코코넛",
    "user_age": "50",
    "user_sex": "F",
    "user_tag1": "계획적인",
    "user_tag2": "여행초보",
    "user_tag3": "사진찍는",
    "user_distance": 3,
    "user_country": "Indonesia",
    "user_travel_start": "2023-01-28",
    "user_travel_end": "2023-09-01",
    "user_image": "https://images.pexels.com/photos/1040882/pexels-photo-1040882.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "d_alt_1fresh"
  },
  {
    "user_id": 49,
    "user_nickname": "드래곤볼",
    "user_age": "50",
    "user_sex": "M",
    "user_tag1": "여행고수",
    "user_tag2": "느긋한",
    "user_tag3": "친화력좋은",
    "user_distance": 4,
    "user_country": "Nigeria",
    "user_travel_start": "2023-06-02",
    "user_travel_end": "2023-09-29",
    "user_image": "https://images.pexels.com/photos/2690774/pexels-photo-2690774.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "z_on_trax"
  },
  {
    "user_id": 50,
    "user_nickname": "스타벅스",
    "user_age": "50",
    "user_sex": "F",
    "user_tag1": "즉흥적인",
    "user_tag2": "계획없는",
    "user_tag3": "FLEX",
    "user_distance": 5,
    "user_country": "Poland",
    "user_travel_start": "2023-01-04",
    "user_travel_end": "2023-10-18",
    "user_image": "https://images.pexels.com/photos/3772510/pexels-photo-3772510.jpeg?auto=compress&cs=tinysrgb&w=400",
    "user_sns": "p_annier_1"
  }
]

export default modalData